const Tasks = {
    '1': {
        title: 'Turn off lights when not in use',
        description: 'Turning off lights when you leave a room can save a lot of energy.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '2': {
        title: 'Take shorter showers',
        description: 'Taking shorter showers can save a lot of water.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '3': {
        title: 'Use a reusable water bottle',
        description: 'Using a reusable water bottle can save a lot of plastic.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '4': {
        title: 'Eat less meat',
        description: 'Eating less meat can reduce your carbon footprint.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '5': {
        title: 'Walk or bike instead of driving',
        description: 'Walking or biking instead of driving can reduce your carbon footprint.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '6': {
        title: 'Plant a tree',
        description: 'Planting a tree can help offset your carbon footprint.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '7': {
        title: 'Use a reusable bag',
        description: 'Using a reusable bag can save a lot of plastic.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '8': {
        title: 'Unplug electronics when not in use',
        description: 'Unplugging electronics when not in use can save a lot of energy.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '9': {
        title: 'Use a reusable coffee cup',
        description: 'Using a reusable coffee cup can save a lot of plastic.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
    '10': {
        title: 'Turn off the tap when brushing your teeth',
        description: 'Turning off the tap when brushing your teeth can save a lot of water.',
        points: 10,
        user: "",
        streak: 0,
        maxStreak: 0,
        level: 0,
        goal: 5,
        daysComplete: 0,
        taskEmmisionSaved: 10,
    },
};

export default Tasks;